import React, { useState, useEffect, useCallback } from 'react';
import { type GstAudit, gstAuditService } from '../../services/gstAuditService';
import { Card } from '../../components/ui/Card';
import { ShieldAlert, CheckCircle2, AlertTriangle, HelpCircle, Loader2 } from 'lucide-react';

interface GstAuditItcTabProps {
  audit: GstAudit;
}

interface ItcData {
  books_itc: number;
  gstr2b_itc: number;
  matched_itc: number;
  missing_in_2b_itc: number;
  unclaimed_2b_itc: number;
  difference: number;
  records_count: {
    purchases: number;
    gstr2b: number;
    matched: number;
    missing_in_2b: number;
    missing_in_books: number;
    mismatch: number;
  };
}

export const GstAuditItcTab: React.FC<GstAuditItcTabProps> = ({ audit }) => {
  const [itcData, setItcData] = useState<ItcData | null>(null);
  const [loading, setLoading] = useState<boolean>(true);

  const loadItcData = useCallback(async () => {
    try {
      setLoading(true);
      const res = await gstAuditService.getItcAnalysis(audit.id);
      setItcData(res.data);
    } catch (err: unknown) {
      console.error('Failed to load ITC analysis', err);
    } finally {
      setLoading(false);
    }
  }, [audit.id]);

  useEffect(() => {
    loadItcData();
  }, [loadItcData]);

  const formatCurrency = (val: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0,
    }).format(val);
  };

  if (loading) {
    return (
      <div className="p-16 text-center text-xs text-[#888888] flex items-center justify-center gap-2">
        <Loader2 className="w-5 h-5 animate-spin text-black" />
        Calculating ITC eligibility & 2B reconciliations...
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Mandatory Statutory Notice */}
      <div className="p-4 bg-blue-50/70 border border-blue-200 rounded-2xl flex items-start gap-3 text-xs text-blue-900">
        <ShieldAlert className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
        <div>
          <p className="font-bold text-blue-950">Statutory Notice on Input Tax Credit (ITC)</p>
          <p className="mt-0.5 text-blue-800 leading-relaxed">
            GSTR-2B is an auto-drafted ITC statement generated by the GST Portal. Invoices present in the Purchase
            Register but not appearing in GSTR-2B are flagged as <strong className="text-blue-950">"Requires Professional Review"</strong>.
            The system does <em>not</em> conclude that an ITC item is legally invalid or ineligible solely because it is missing from 2B
            (e.g., supplier filing delay, quarter filers under QRMP, or cutoff discrepancies).
          </p>
        </div>
      </div>

      {/* ITC Summary Counters */}
      {itcData && (
        <>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3.5">
            <Card className="p-4 border-[#E5E5E5] bg-white">
              <span className="text-[11px] font-bold text-[#888888] uppercase tracking-wider block mb-1">
                ITC as per Books
              </span>
              <p className="text-xl font-mono font-black text-[#111111]">
                {formatCurrency(itcData.books_itc)}
              </p>
              <p className="text-[11px] text-[#666666] mt-1 font-mono">
                {itcData.records_count.purchases} Purchase Invoices
              </p>
            </Card>

            <Card className="p-4 border-[#E5E5E5] bg-white">
              <span className="text-[11px] font-bold text-[#888888] uppercase tracking-wider block mb-1">
                ITC as per GSTR-2B
              </span>
              <p className="text-xl font-mono font-black text-blue-700">
                {formatCurrency(itcData.gstr2b_itc)}
              </p>
              <p className="text-[11px] text-[#666666] mt-1 font-mono">
                {itcData.records_count.gstr2b} Portal Invoices
              </p>
            </Card>

            <Card className="p-4 border-[#E5E5E5] bg-white">
              <span className="text-[11px] font-bold text-[#888888] uppercase tracking-wider block mb-1">
                Reconciled & Matched ITC
              </span>
              <p className="text-xl font-mono font-black text-emerald-600">
                {formatCurrency(itcData.matched_itc)}
              </p>
              <p className="text-[11px] text-emerald-700 font-medium mt-1">
                {itcData.records_count.matched} Invoices Verified
              </p>
            </Card>

            <Card className="p-4 border-[#E5E5E5] bg-white">
              <span className="text-[11px] font-bold text-[#888888] uppercase tracking-wider block mb-1">
                ITC Variance Difference
              </span>
              <p className={`text-xl font-mono font-black ${itcData.difference > 0 ? 'text-amber-600' : 'text-emerald-700'}`}>
                {formatCurrency(itcData.difference)}
              </p>
              <p className="text-[11px] text-[#666666] mt-1">
                {itcData.difference > 0 ? 'Excess claimed in books' : 'Excess available in 2B'}
              </p>
            </Card>
          </div>

          {/* ITC Reconciliation Matrix */}
          <Card className="p-5 border-[#E5E5E5] bg-white">
            <h4 className="text-sm font-bold text-[#111111] mb-4">ITC Classification & Risk Assessment</h4>

            <div className="space-y-3 text-xs">
              <div className="p-3.5 bg-emerald-50/60 border border-emerald-200 rounded-xl flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                  <div>
                    <p className="font-bold text-emerald-950">Matched & Eligible ITC</p>
                    <p className="text-[11px] text-emerald-800">
                      Invoices matched across Supplier GSTIN, invoice number, and tax values between Books and GSTR-2B.
                    </p>
                  </div>
                </div>
                <div className="text-right shrink-0 font-mono">
                  <p className="font-bold text-emerald-950 text-sm">{formatCurrency(itcData.matched_itc)}</p>
                  <p className="text-[10px] text-emerald-700">{itcData.records_count.matched} records</p>
                </div>
              </div>

              <div className="p-3.5 bg-amber-50/60 border border-amber-200 rounded-xl flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
                  <div>
                    <p className="font-bold text-amber-950">ITC in Books but Missing in GSTR-2B</p>
                    <p className="text-[11px] text-amber-800">
                      Invoices booked in purchase register for which supplier GSTR-1 filing is not yet reflected in 2B. Requires supplier follow-up.
                    </p>
                  </div>
                </div>
                <div className="text-right shrink-0 font-mono">
                  <p className="font-bold text-amber-950 text-sm">{formatCurrency(itcData.missing_in_2b_itc)}</p>
                  <p className="text-[10px] text-amber-700">{itcData.records_count.missing_in_2b} records</p>
                </div>
              </div>

              <div className="p-3.5 bg-blue-50/60 border border-blue-200 rounded-xl flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <HelpCircle className="w-4 h-4 text-blue-600 shrink-0" />
                  <div>
                    <p className="font-bold text-blue-950">GSTR-2B Credit Not Yet Booked</p>
                    <p className="text-[11px] text-blue-800">
                      Available credit in GSTR-2B not identified in current purchase register. May represent unbooked invoices or omitted expenses.
                    </p>
                  </div>
                </div>
                <div className="text-right shrink-0 font-mono">
                  <p className="font-bold text-blue-950 text-sm">{formatCurrency(itcData.unclaimed_2b_itc)}</p>
                  <p className="text-[10px] text-blue-700">{itcData.records_count.missing_in_books} records</p>
                </div>
              </div>
            </div>
          </Card>
        </>
      )}
    </div>
  );
};
